#!/usr/bin/env bash
# install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
chmod u+x /var/www/html/index.nginx-debian.html
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start

