#!/usr/bin/env bash
#install load balancer

apt update
apt install -y haproxy=1.6.\*

printf %s "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
    balance roundrobin
    server 3293-web-01 34.138.95.23:80 check
    server 3293-web-02 18.212.250.192:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
