#!/usr/bin/env bash
#Bash script that
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/my.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/holbertonscript.pid

while true
do
echo "To infinity and beyond!"
trap 'I hate the kill command' SIGTERM
trap 'Y U no love me?!' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT
trap 'rm /var/run/myscript.pid' SIGTERM
sleep 2
done
