#!/usr/bin/env bash
#Write Bash (init) script 101-manage_my_process that manages manage_my_process
#When passing the argument start:
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process started
#When passing the argument stop:
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Displays manage_my_process stopped
#When passing the argument restart
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process restarted
#Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

case "$1" in

    start)
	/etc/init.d/manage_my_process start
	echo "manage_my_process started"
	echo "$$" > "/var/run/my_process.pid"
	;;

    stop)
	/etc/init.d/manage_my_process stop
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;

    restart)
	/etc/init.d/manage_my_process stop
	rm -f /var/run/my_process.pid
	/etc/init.d/manage_my_process start
	echo "$$" > "/var/run/my_process.pid"
	echo "manage_my_process restarted"
	;;

    *)

	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
