#!/bin/bash
# script that displays Best School 10 times, but for the 9th iteration, displays 
#Best School and then Hi on a new line

c=1
while [ $c -le 10 ]
do
    echo "Best School"
    c=$(( c + 1))
if [ $c == 10 ]
    then
      echo "Hi"
    fi
done
