#!/usr/bin/env bash
#script that displays:
#1-The content of the current directory
#2-In a list format
#3-Where only the part of the name after the first dash is displayed

for file in *
do
    echo $file | cut -d "-" -f2
done
