#!/usr/bin/env bash
#nginx must be running as nginx user
#nginx must be listening on all active IPs on port 8080
#You cannot use apt-get remove
#Write a Bash script that configures the container to fit the above requirement

pkill apache2
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
